$version Generated by VerilatedVcd $end
$timescale 1ns $end
 $scope module decoder_4_to_16_tb $end
  $var wire 4 " addr [3:0] $end
  $var wire 16 # one_hot [15:0] $end
  $var wire 32 $ i [31:0] $end
  $scope module DUT $end
   $var wire 4 " addr [3:0] $end
   $var wire 16 # one_hot [15:0] $end
   $scope module genblk1[0] $end
    $scope module ld $end
     $var wire 4 5 select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 % single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[10] $end
    $scope module ld $end
     $var wire 4 6 select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 & single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[11] $end
    $scope module ld $end
     $var wire 4 7 select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 ' single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[12] $end
    $scope module ld $end
     $var wire 4 8 select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 ( single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[13] $end
    $scope module ld $end
     $var wire 4 9 select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 ) single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[14] $end
    $scope module ld $end
     $var wire 4 : select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 * single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[15] $end
    $scope module ld $end
     $var wire 4 ; select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 + single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[1] $end
    $scope module ld $end
     $var wire 4 < select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 , single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[2] $end
    $scope module ld $end
     $var wire 4 = select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 - single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[3] $end
    $scope module ld $end
     $var wire 4 > select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 . single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[4] $end
    $scope module ld $end
     $var wire 4 ? select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 / single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[5] $end
    $scope module ld $end
     $var wire 4 @ select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 0 single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[6] $end
    $scope module ld $end
     $var wire 4 A select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 1 single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[7] $end
    $scope module ld $end
     $var wire 4 B select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 2 single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[8] $end
    $scope module ld $end
     $var wire 4 C select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 3 single_wire $end
    $upscope $end
   $upscope $end
   $scope module genblk1[9] $end
    $scope module ld $end
     $var wire 4 D select [3:0] $end
     $var wire 4 " addr [3:0] $end
     $var wire 1 4 single_wire $end
    $upscope $end
   $upscope $end
  $upscope $end
 $upscope $end
$enddefinitions $end


#0
b0000 "
b0000000000000001 #
b00000000000000000000000000000000 $
1%
0&
0'
0(
0)
0*
0+
0,
0-
0.
0/
00
01
02
03
04
b0000 5
b1010 6
b1011 7
b1100 8
b1101 9
b1110 :
b1111 ;
b0001 <
b0010 =
b0011 >
b0100 ?
b0101 @
b0110 A
b0111 B
b1000 C
b1001 D
#1
b1001 "
b0000001000000000 #
b00000000000000000000000000000001 $
0%
14
#2
b0111 "
b0000000010000000 #
b00000000000000000000000000000010 $
12
04
#3
b1101 "
b0010000000000000 #
b00000000000000000000000000000011 $
1)
02
#4
b0011 "
b0000000000001000 #
b00000000000000000000000000000100 $
0)
1.
#5
b1000 "
b0000000100000000 #
b00000000000000000000000000000101 $
0.
13
#6
b0100 "
b0000000000010000 #
b00000000000000000000000000000110 $
1/
03
#7
b0000 "
b0000000000000001 #
b00000000000000000000000000000111 $
1%
0/
#8
b1111 "
b1000000000000000 #
b00000000000000000000000000001000 $
0%
1+
#9
b0111 "
b0000000010000000 #
b00000000000000000000000000001001 $
0+
12
#10
b00000000000000000000000000001010 $
