$version Generated by VerilatedVcd $end
$timescale 1ns $end
 $scope module one_bit_comparator_structural_tb $end
  $var wire 1 " a $end
  $var wire 1 # b $end
  $var wire 1 $ greater $end
  $var wire 1 % less $end
  $var wire 1 & equal $end
  $scope module DUT $end
   $var wire 1 " a $end
   $var wire 1 # b $end
   $var wire 1 $ greater $end
   $var wire 1 % less $end
   $var wire 1 & equal $end
   $var wire 1 ' a_not $end
   $var wire 1 ( b_not $end
  $upscope $end
 $upscope $end
$enddefinitions $end


#0
0"
0#
0$
0%
1&
1'
1(
#1
1#
1%
0&
0(
#2
1"
0#
1$
0%
0'
1(
#3
1#
0$
1&
0(
#4
