$version Generated by VerilatedVcd $end
$timescale 1ns $end
 $scope module shift_register_structural_tb $end
  $var wire 1 " in $end
  $var wire 4 # prev_out [3:0] $end
  $var wire 1 $ clk $end
  $var wire 4 % out [3:0] $end
  $var wire 32 & i [31:0] $end
  $scope module DUT $end
   $var wire 1 " in $end
   $var wire 1 $ clk $end
   $var wire 4 % out [3:0] $end
   $var wire 1 ' Q1 $end
   $var wire 1 ( Q2 $end
   $var wire 1 ) Q3 $end
   $var wire 1 * Q4 $end
   $var wire 1 + Q1n $end
   $var wire 1 , Q2n $end
   $var wire 1 - Q3n $end
   $var wire 1 . Q4n $end
   $scope module dff_1 $end
    $var wire 1 " D $end
    $var wire 1 $ clk $end
    $var wire 1 ' Q $end
    $var wire 1 + Qn $end
    $var wire 1 / n1 $end
    $var wire 1 0 n2 $end
    $var wire 1 ' n3 $end
    $var wire 1 + n4 $end
    $var wire 1 1 Dn $end
   $upscope $end
   $scope module dff_2 $end
    $var wire 1 ' D $end
    $var wire 1 $ clk $end
    $var wire 1 ( Q $end
    $var wire 1 , Qn $end
    $var wire 1 2 n1 $end
    $var wire 1 3 n2 $end
    $var wire 1 ( n3 $end
    $var wire 1 , n4 $end
    $var wire 1 4 Dn $end
   $upscope $end
   $scope module dff_3 $end
    $var wire 1 ( D $end
    $var wire 1 $ clk $end
    $var wire 1 ) Q $end
    $var wire 1 - Qn $end
    $var wire 1 5 n1 $end
    $var wire 1 6 n2 $end
    $var wire 1 ) n3 $end
    $var wire 1 - n4 $end
    $var wire 1 7 Dn $end
   $upscope $end
   $scope module dff_4 $end
    $var wire 1 ) D $end
    $var wire 1 $ clk $end
    $var wire 1 * Q $end
    $var wire 1 . Qn $end
    $var wire 1 8 n1 $end
    $var wire 1 9 n2 $end
    $var wire 1 * n3 $end
    $var wire 1 . n4 $end
    $var wire 1 : Dn $end
   $upscope $end
  $upscope $end
 $upscope $end
$enddefinitions $end


#0
0"
b0000 #
0$
b0111 %
b00000000000000000000000000000000 &
1'
1(
1)
0*
0+
0,
0-
1.
1/
10
11
12
13
04
15
16
07
18
19
0:
#4
1$
b0000 %
0'
0(
0)
1+
1,
1-
00
03
14
06
17
09
1:
#8
0$
10
13
16
19
#12
1$
00
03
06
09
#16
0$
10
13
16
19
#20
1$
00
03
06
09
#24
0$
10
13
16
19
#28
1$
00
03
06
09
#32
0$
10
13
16
19
#36
1$
00
03
06
09
#40
1"
0$
b1111 %
b00000000000000000000000000000001 &
1'
1(
1)
1*
0+
0,
0-
0.
10
01
13
04
16
07
19
0:
#44
b1111 #
1$
0/
02
05
08
#48
0$
b00000000000000000000000000000010 &
1/
12
15
18
#52
1$
0/
02
05
08
#56
0$
b00000000000000000000000000000011 &
1/
12
15
18
#60
1$
0/
02
05
08
#64
0$
b00000000000000000000000000000100 &
1/
12
15
18
#68
1$
0/
02
05
08
#72
0"
0$
b0000 %
b00000000000000000000000000000101 &
0'
0(
0)
0*
1+
1,
1-
1.
1/
11
12
14
15
17
18
1:
#76
b0000 #
1$
00
03
06
09
#80
0$
b00000000000000000000000000000110 &
10
13
16
19
#84
1$
00
03
06
09
#88
0$
b00000000000000000000000000000111 &
10
13
16
19
#92
1$
00
03
06
09
#96
1"
0$
b1111 %
b00000000000000000000000000001000 &
1'
1(
1)
1*
0+
0,
0-
0.
10
01
13
04
16
07
19
0:
#100
b1111 #
1$
0/
02
05
08
#104
0$
b00000000000000000000000000001001 &
1/
12
15
18
#108
1$
0/
02
05
08
#112
0$
b00000000000000000000000000001010 &
1/
12
15
18
#116
1$
0/
02
05
08
#120
0$
b00000000000000000000000000001011 &
1/
12
15
18
#124
1$
0/
02
05
08
#128
0$
b00000000000000000000000000001100 &
1/
12
15
18
#132
1$
0/
02
05
08
#136
0"
0$
b0000 %
b00000000000000000000000000001101 &
0'
0(
0)
0*
1+
1,
1-
1.
1/
11
12
14
15
17
18
1:
#140
b0000 #
1$
00
03
06
09
#144
1"
0$
b1111 %
b00000000000000000000000000001110 &
1'
1(
1)
1*
0+
0,
0-
0.
10
01
13
04
16
07
19
0:
#148
b1111 #
1$
0/
02
05
08
#152
0"
0$
b0000 %
b00000000000000000000000000001111 &
0'
0(
0)
0*
1+
1,
1-
1.
1/
11
12
14
15
17
18
1:
#156
b0000 #
1$
00
03
06
09
#160
0$
b00000000000000000000000000010000 &
10
13
16
19
