$version Generated by VerilatedVcd $end
$timescale 1ns $end
 $scope module simple_counter_tb $end
  $var wire 1 " reset $end
  $var wire 1 # clk $end
  $var wire 2 $ counter [1:0] $end
  $scope module DUT $end
   $var wire 1 # clk $end
   $var wire 1 " reset $end
   $var wire 2 $ counter_out [1:0] $end
   $var wire 2 $ counter [1:0] $end
  $upscope $end
 $upscope $end
$enddefinitions $end


#0
1"
0#
b00 $
#4
1#
#8
0#
#10
0"
#12
1#
b01 $
#16
0#
#20
1#
b10 $
#24
0#
#28
1#
b11 $
#32
0#
#36
1#
b00 $
#40
0#
#44
1#
b01 $
#47
1"
b00 $
#48
0#
